### PR TITLE
sonar cube test

### PR DESCRIPTION
**Pull request by dicley**

### CODE REVIEW

**Comment by winterer** [comment]
You should probably try the following settings in `.github/workflows/build.yml`:
```
      ...
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
```

**Comment by winterer** [comment]
OK, you're close now.
Automatic analysis requires one initial manually run analysis.
This should do the trick: `mvn -B clean verify sonar:sonar -Dsonar.login=<your-secret-token>`

**Comment by dicley** [comment]
Thank you. I actually have that one too in the yml file not "verify" though.
`run: mvn -B clean compile sonar:sonar -Dsonar.login=${{ secrets.SONAR_TOKEN }}`
 I have also tried locally but im keep getting "You're not authorized to run analysis. Please contact the project administrator." error.

**Comment by winterer** [comment]
If you run the analysis locally via command line, you cannot use `${{ secrets.SONAR_TOKEN }}` as SonarCube secret, as this variable is only available in the GitHub environment (you defined this secret there). Instead, you must use the 'real' secret instead (e.g. `... -Dsonar.login=087544b3...`).
I've already done this for you, so from now on, automatic analysis should work on every push/pull request.

**Comment by dicley** [comment]
Thank you 🙏 working fine also locally too.

**Pull request merged**
